add support for lm_sensors as data source

diff --git a/templog b/templog
--- a/templog
+++ b/templog
@@ -1,8 +1,6 @@
-#!/bin/bash
+#!/bin/sh
 # templog logs cpu temperature to /var/log/temp.log 
 
-# location of system file with the temperature
-SYS_TEMP_FILE='/sys/class/thermal/thermal_zone0/temp' 
 # log file location 
 LOG_DIR="/var/log"
 LOG_FILE="$LOG_DIR/temp.log"
@@ -23,9 +21,29 @@ create_log_file () {
 }
 
 log_temp () {
-    #DATE=$(date +'%Y-%m-%d %H:%M')
+	# location of system file with the temperature
+	SYS_TEMP_FILE='/sys/class/thermal/thermal_zone0/temp' 
+	
+	# check if temperature file exists, otherwise use lm_sensors
+	if [ -a $SYS_TEMP_FILE ]; then
+    	TEMP=$(head -n 1 $SYS_TEMP_FILE | xargs -I{} awk "BEGIN {printf \"%.2f\n\", {}/1000}")
+	else
+		if [ -a "$HOME"/.templogrc ]; then
+			. "$HOME"/.templogrc	
+			TEMP=$(sensors -u ${SENSOR1} | grep temp1_input | awk '{printf "%.1f", $2}')
+		else
+			echo "Could not find $SYS_TEMP_FILE nor $HOME/.templogrc."
+			echo ""
+			echo "Create a file $HOME/.templogrc with a variable SENSOR1 containing the name of the sensor you want to measure with command 'sensors' (dep: lm_sensors)."
+			echo ""
+			echo "For example, insert the desired <sensor> in the following command:"
+			echo ""
+			echo 'echo "SENSOR1=<sensor>" >> ${HOME}/.templogrc'
+			exit 2
+		fi
+	fi
+
 	TIME=$(date +%s)
-    TEMP=$(head -n 1 $SYS_TEMP_FILE | xargs -I{} awk "BEGIN {printf \"%.2f\n\", {}/1000}")
     LOG_STRING="$TIME $TEMP"
     echo "$LOG_STRING" >> $LOG_FILE 
 }
